### ISSUE TITLE
Error "TypeError: Cannot read property 'slice' of undefined"

### ISSUE THREAD

**Issue by monperrus** [xwiki-labs/cryptpad-tools#3]
Thanks a lot for Cryptpad!

I'm trying to download a pad as follows:

    node ./dot.js <url of a given pad>

However, I hit the error below. Any idea?

```
/tmp/cryptpad-tools/dump.js:61
            const padFile = fileHost + '/datastore/' + secret.channel.slice(0,2) + '/' + secret.channel + '.ndjson';
                                                                      ^

TypeError: Cannot read property 'slice' of undefined
    at w (/tmp/cryptpad-tools/dump.js:61:71)
    at f (/tmp/cryptpad-tools/node_modules/nthen/index.js:29:26)
    at waitFor (/tmp/cryptpad-tools/node_modules/nthen/index.js:39:17)
    at Object.execCb (/tmp/cryptpad-tools/node_modules/requirejs/bin/r.js:1946:33)
    at Module.check (/tmp/cryptpad-tools/node_modules/requirejs/bin/r.js:1133:51)
    at Module.enable (/tmp/cryptpad-tools/node_modules/requirejs/bin/r.js:1426:22)
    at Module.init (/tmp/cryptpad-tools/node_modules/requirejs/bin/r.js:1038:26)
    at Timeout._onTimeout (/tmp/cryptpad-tools/node_modules/requirejs/bin/r.js:1710:36)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)

```

**Comment by monperrus** [comment]
FTR, same error today.

**Comment by monperrus** [comment]
Same error with node v12.22.9 

cc/ @ansuz
